name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create archive
        run: |
          zip -j android-lptools.zip bin/*

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.ref_name }}
          files: android-lptools.zip
          body_path: ${{ github.workspace }}/RELEASE_NOTES.md
          generate_release_notes: ${{ !hashFiles('RELEASE_NOTES.md') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 